---
title: "Final 222 Project"
output:
  pdf_document: default
  html_document: default
date: "2026-03-02"
---

Libraries

```{r}
library(nhanesA)
library(purrr)
library(dplyr)
library(ggplot2)
library(survey)
library(svydiags)
library(mgcv)
library(splines)
```

Retrieving Nhanes Data

```{r}
dfs = list(
  demographics = nhanes("DEMO_I"),
  chloestral   = nhanes("BPQ_I"),
  cardio       = nhanes("CDQ_I"),
  diabetes     = nhanes("DIQ_I"),
  diet         = nhanes("DBQ_I"),
  disability   = nhanes("DLQ_I"),
  drugs        = nhanes("DUQ_I"),
  food_sec     = nhanes("FSQ_I"),
  housing      = nhanes("HOQ_I"),
  income       = nhanes("INQ_I"),
  conditions   = nhanes("MCQ_I"),
  activity     = nhanes("PAQ_I"),
  kidney       = nhanes("KIQ_U_I"),
  occuptation  = nhanes("OCQ_I"),
  mental       = nhanes("DPQ_I")
)

df = reduce(dfs, left_join, by = "SEQN")
```

Creating Dataframe

```{r}
## creating new cardiovascular health outcome
df <- df %>%
  mutate(
    cardio = if_else(
      MCQ160B == "Yes" |
      MCQ160C == "Yes" |
      MCQ160D == "Yes" |
      MCQ160E == "Yes",
      1, 0
    )
  )

## only selecting columns with variables we are going to put into the model
df <- df %>%
dplyr::select(RIDRETH3, RIDAGEYR, RIAGENDR, INDFMPIR, DMDEDUC2, cardio, SDMVPSU, SDMVSTRA, WTINT2YR)
## 9,971 entries 

## getting rid of any rows with NA values
df <- na.omit(df)
## 5,082 entries (this eliminates anyone under 20 since cardiovasuclar variables were only for people above 20)

## rename columns to make more sense 
df <- df %>%
  rename(
    race = RIDRETH3,
    age = RIDAGEYR,
    gender = RIAGENDR,
    income = INDFMPIR,
    education = DMDEDUC2
  )

## combining mexican american and other hispanic into just one category: hispanic
df <- df %>%
  mutate(
    race = case_when(
      race %in% c("Mexican American", "Other Hispanic") ~ "Hispanic",
      TRUE ~ race
    )
  )

## getting rid of rows with education as don't know
df <- df %>%
  filter(education != "Don't Know")

## combining 9-11th grade and less than 9th grade 
df <- df %>%
  mutate(
    education = case_when(
      education %in% c(
        "Less than 9th grade",
        "9-11th grade (Includes 12th grade with no diploma)"
      ) ~ "Not High School Graduate",
      TRUE ~ education
    )
  )

## combining Some College or AA degree and High School Grad/GED or Equivalent
df <- df %>%
  mutate(
    education = case_when(
      education %in% c("High school graduate/GED or equivalent",
                       "Some college or AA degree") ~ "High School Graduate",
      TRUE ~ education
    )
  )


```

Analysis

```{r}
## checking variable type 
df$cardio    <- as.factor(df$cardio)
df$education <- as.factor(df$education)
df$gender    <- as.factor(df$gender)
df$race      <- as.factor(df$race)

## changing reference variables 
df$education <- relevel(as.factor(df$education),
                        ref = "Not High School Graduate")

df$race <- relevel(as.factor(df$race),
                   ref = "Non-Hispanic White")
```


```{r}
## exploratory data analysis 

df %>%
  group_by(education) %>%
  summarise(prop_cardio = mean(cardio == 1)) %>%
  ggplot(aes(x = education, y = prop_cardio)) +
  geom_col() +
  labs(
    x = "Education Level",
    y = "Proportion with Cardiovascular Disease",
    title = "Cardiovascular Disease by Education Level"
  ) +
  theme_minimal()
```



```{r}
## survey weights

nhc = svydesign(
id =~SDMVPSU,
strata = ~SDMVSTRA,
weights = ~WTINT2YR,
data = df,
nest = TRUE
)
```


```{r}
# Research Question: Is education associated with cardiovascular health outcomes? Does education have stronger health effects for women than men? 

## no interaction term 
model_svy <- svyglm(cardio ~ education + gender + I(age^2) + age + race + income,
design = nhc,family = quasibinomial())
summary(model_svy)
## this is saying women in general while holding our other confounders constant have less cardiovasucular problems 
## holding gender, age, race, and income constant, education is not a statistically significant predictor for cardiovascular health outcomes
## but, holding education, age, race, and income constant, gender is a statistically significant predictor for cardiovasuclar health otucomes 
```



Table
```{r}
# Model 1 table
coef <- summary(model_svy)$coefficients
ci   <- confint(model_svy)

table1 <- cbind(
  est = coef[, 1],
  OR = exp(coef[, 1]),
  CI = exp(ci),
  p_value = coef[, ncol(coef)]
)

round(table1, 3)
```

Got all of my Diagnostic Ideas from here:
https://cran.r-project.org/web/packages/svydiags/svydiags.pdf
```{r}
cd = svyCooksD(model_svy,"SDMVSTRA","SDMVPSU",doplot = F)
```

```{r}
#computes the leverages from a model fitted with complex survey data
h = svyhat(model_svy)
```

```{r}
#computes the standardized residuals, i.e., the residuals divided by an estimate of the
#model standard deviation of the residuals.
res = svystdres(model_svy, "SDMVSTRA","SDMVPSU", doplot = T)
```

```{r}
#computes variance inflation factors
X = model.matrix(~education + gender + I(age^2) + age + race + income,
                 data = model.frame(model_svy))
rows_used = as.numeric(names(model_svy$y))
w = weights(nhc)[rows_used]

svyvif(model_svy, X[,-1], w,"SDMVSTRA","SDMVPSU")
```

```{r}
#the amount that a parameter estimate changes when the unit is deleted from the sample
#$cutoff(2/sqrt(n)): 0.377269
dfb = svydfbetas(model_svy,"SDMVSTRA","SDMVPSU",3)
apply(abs(dfb$Dfbetas)>dfb$cutoff,1,sum)
```

```{r}
#the amount that a unit’s predicted value changes when the unit is deleted from the sample.
#$cutoff: 0.121539
dff=svydffits(model_svy,"SDMVSTRA","SDMVPSU",4)
sum(abs(dff$Dffits) > dff$cutoff)
```

```{r}
# Cook's distance vs fitted values
plot(fitted(model_svy), cd,
     xlab = "Fitted Values",
     ylab = "Cook's Distance",
     main = "Cook's Distance vs Fitted Values")
abline(h = c(2,3), lty = 2,lwd = 3,col ="red")
```
```{r}
# Cook's distance vs leverage
plot(h, cd,
     xlab = "Leverage",
     ylab = "Cook's Distance",
     main = "Cook's Distance vs Leverage")
abline(v = 3 * mean(h), lty = 2, lwd=3, col = "red")
abline(h = c(2, 3), lty = 2, lwd = 3, col = "green")
```
```{r}
#Leverage vs Fitted Values
plot(fitted(model_svy),h,
     xlab = "Fitted Values",
     ylab = "Leverage",
     main = "Leverage vs Fitted Values")
abline(h = 3 * mean(h, na.rm = TRUE), lty = 2, lwd = 3, col = "red")
```

```{r}
# Standardized residuals vs fitted values
plot(fitted(model_svy), res$stdresids,
     xlab = "Fitted values",
     ylab = "Standardized Residuals",
     main = "Standardized Residuals vs Fitted Values")
abline(h = c(-3, 3), lty = 2, lwd = 3, col = "red")
```

```{r}
# Standardized residuals vs leverage
plot(h, res$stdresids,
     xlab = "Leverage",
     ylab = "Standardized Residuals",
     main = "Standardized Residuals vs Leverage")
abline(v = 3 * mean(h), lty = 2,lwd=3, col = "green")
abline(h = c(-3, 3), lty = 2,lwd=3, col = "red")
```



```{r}
# interaction term
model_int_svy <- svyglm(cardio ~ education * gender + I(age^2) + age + race + income,
design = nhc,family = quasibinomial())
summary(model_int_svy)
```


```{r}
anova(model_svy, model_int_svy)
```
Table
```{r}
coef <- summary(model_int_svy)$coefficients
ci   <- confint(model_int_svy)

table1 <- cbind(
  est = coef[, 1],
  OR = exp(coef[, 1]),
  CI = exp(ci),
  p_value = coef[, ncol(coef)]
)

round(table1, 3)
```

```{r}
cd = svyCooksD(model_int_svy,"SDMVSTRA","SDMVPSU")
```

```{r}
h = svyhat(model_int_svy)
```

```{r}
res = svystdres(model_int_svy, "SDMVSTRA","SDMVPSU", doplot = F)
```

```{r}
X = model.matrix(~education + gender + I(age^2) + age + race + income,
                 data = model.frame(model_int_svy))
rows_used = as.numeric(names(model_int_svy$y))
w = weights(nhc)[rows_used]

svyvif(model_int_svy, X[,-1], w,"SDMVSTRA","SDMVPSU")
```

```{r}
#$cutoff(2/sqrt(n)): 0.3808568
dfb = svydfbetas(model_int_svy,"SDMVSTRA","SDMVPSU",3)
apply(abs(dfb$Dfbetas)>dfb$cutoff,1,sum)
```

```{r}
#$cutoff: 0.1371678
dff=svydffits(model_int_svy,"SDMVSTRA","SDMVPSU",4)
dff$cutoff
sum(abs(dff$Dffits) > dff$cutoff)
```

```{r}
# Cook's distance vs fitted values
plot(fitted(model_int_svy), cd,
     xlab = "Fitted Values",
     ylab = "Cook's Distance",
     main = "Cook's Distance vs Fitted Values")
abline(h = c(2,3), lty = 2, lwd =3, col = "red")
```

```{r}
# Cook's distance vs leverage
plot(h, cd,
     xlab = "Leverage",
     ylab = "Cook's Distance",
     main = "Cook's Distance vs Leverage")
abline(v = 3 * mean(h), lty = 2,col = "green")
abline(h = c(2, 3), lty = 2,lwd = 3, col ="red")
```

```{r}
#Leverage vs Fitted Values
plot(fitted(model_int_svy),h,
     xlab = "Fitted Values",
     ylab = "Leverage",
     main = "Leverage vs Fitted Values")
abline(h = 3 * mean(h, na.rm = TRUE), lty = 2, lwd = 3, col = "red")
```

```{r}
# Standardized residuals vs fitted values
plot(fitted(model_int_svy), res$stdresids,
     xlab = "Fitted values",
     ylab = "Standardized Residuals",
     main = "Standardized Residuals vs Fitted Values")
abline(h = c(-3, 3), lty = 2,lwd=3, col = "red")
```

```{r}
# Standardized residuals vs leverage
plot(h, res$stdresids,
     xlab = "Leverage",
     ylab = "Standardized Residuals",
     main = "Standardized Residuals vs Leverage")
abline(v = 3 * mean(h), lty = 2,lwd=3, col = "green")
abline(h = c(-3, 3), lty = 2,lwd=3, col = "red")

```


```{r}
df$fitted <- fitted(model_svy)

# create bins of predicted probabilities
df$bin <- cut(df$fitted, breaks = quantile(df$fitted, probs = seq(0,1,0.1)),
              include.lowest = TRUE)

# compute observed versus predicted probabilities  
obs_fit <- aggregate(cbind(cardio, fitted) ~ bin, data = df, mean)

plot(obs_fit$fitted, obs_fit$cardio- 1,
     xlab = "Predicted Probability",
     ylab = "Observed Probability",
     pch = 19,
     main = "Observed vs Predicted Cardiovascular Outcomes No Int")

abline(0,1,lwd=2,col="red")

```

```{r}
df$fitted <- fitted(model_int_svy)

# create bins of predicted probabilities
df$bin <- cut(df$fitted, breaks = quantile(df$fitted, probs = seq(0,1,0.1)),
              include.lowest = TRUE)

# compute observed versus predicted probabilities  
obs_fit <- aggregate(cbind(cardio, fitted) ~ bin, data = df, mean)

plot(obs_fit$fitted, obs_fit$cardio- 1,
     xlab = "Predicted Probability",
     ylab = "Observed Probability",
     pch = 19,
     main = "Observed vs Predicted Cardiovascular Outcomes with Int")

abline(0,1,lwd=2,col="red")
```

```{r}

# create age groups
df$age_group <- cut(df$age,
                    breaks = c(20, 30, 35, 40, 45, 50, 55, 60, 65, 70, 80),
                    include.lowest = TRUE,
                    right = FALSE)

# observed probability within each age group
obs_age <- aggregate(cardio ~ age_group, data = df, mean, na.rm = TRUE)

# manual age midpoints for the 10 bins above
obs_age$age_mid <- c(25, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 75)[1:nrow(obs_age)]

# plot points only
plot(obs_age$age_mid, obs_age$cardio01,
     xlab = "Age",
     ylab = "Observed probability",
     xlim = c(20, 80),
     ylim = c(0, 1),
     pch = 1)
```

